use std::env;
use std::path::PathBuf;
use std::process::Command;

use glob::glob;

use bindgen::callbacks::{IntKind, ParseCallbacks};

#[derive(Debug)]
struct DefineParser;

impl ParseCallbacks for DefineParser {
    fn int_macro(&self, _name: &str, value: i64) -> Option<IntKind> {
        if value >= i32::MIN as i64 && value <= i32::MAX as i64 {
            Some(IntKind::I32)
        } else {
            None
        }
    }
}

fn emit_libwg_rerun_inputs() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=libwg/wireguard-go/Makefile");
    println!("cargo:rerun-if-changed=libwg/wireguard-go/go.mod");
    println!("cargo:rerun-if-changed=libwg/wireguard-go/go.sum");

    for entry in glob("libwg/wireguard-go/**/*.go").expect("invalid libwg Go source glob") {
        let path = entry.unwrap_or_else(|err| panic!("failed to read libwg Go source: {err}"));
        if path.file_name().and_then(|name| name.to_str()) != Some("version.go") {
            println!("cargo:rerun-if-changed={}", path.display());
        }
    }
}

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let wireguard_go_dir = manifest_dir.join("libwg").join("wireguard-go");
    let header_path = wireguard_go_dir.join("libwg.h");
    let archive_path = wireguard_go_dir.join("libwg.a");

    if !wireguard_go_dir.join("Makefile").exists() {
        panic!("libwg/wireguard-go is missing. Run: git submodule update --init --recursive");
    }

    emit_libwg_rerun_inputs();

    let make = env::var_os("MAKE").unwrap_or_else(|| "make".into());
    let status = Command::new(make)
        .arg("libwg")
        .current_dir(&wireguard_go_dir)
        .status()
        .expect("failed to run make libwg");

    if !status.success() {
        panic!("make libwg failed with status {status}");
    }

    if !archive_path.exists() {
        panic!("make libwg did not produce {}", archive_path.display());
    }

    if !header_path.exists() {
        panic!("make libwg did not produce {}", header_path.display());
    }

    // Tell Cargo to look for the static libwg archive generated by make.
    println!(
        "cargo:rustc-link-search=native={}",
        wireguard_go_dir.display()
    );
    println!("cargo:rustc-link-lib=static=wg");

    // The bindgen::Builder is the main entry point to bindgen, and lets you build
    // up options for the resulting bindings.
    let bindings = bindgen::Builder::default()
        // The input header we would like to generate bindings for.
        .header(header_path.display().to_string())
        // Tell cargo to invalidate the built crate whenever any of the included
        // header files changed.
        .parse_callbacks(Box::new(bindgen::CargoCallbacks))
        // Parse number define macro as i32 instead of u32.
        .parse_callbacks(Box::new(DefineParser))
        // Finish the builder and generate the bindings.
        .generate()
        // Unwrap the Result and panic on failure.
        .expect("Unable to generate bindings");

    // Write the bindings to the $OUT_DIR/bindings.rs file.
    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap());
    bindings
        .write_to_file(out_path.join("bindings.rs"))
        .expect("Couldn't write bindings!");
}
